// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqrqbfbikggvggkhjjus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xcnFiZmJpa2dndmdna2hqanVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODgyNDQsImV4cCI6MjA1OTM2NDI0NH0.QmAJ92QDo7uAN1svbQfjPKK2BOaTL5VHCr_KbLCB5jY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);